# Generated by Django 5.0.4 on 2024-06-03 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banner_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="main_banner",
            name="added_at",
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name="sub_banner",
            name="added_at",
            field=models.DateField(auto_now=True),
        ),
    ]
