# Generated by Django 5.0.4 on 2024-04-20 04:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("category_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="product_color_image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_color", models.CharField(max_length=30)),
                ("image_first", models.ImageField(upload_to="product/")),
                ("image_second", models.ImageField(upload_to="product/")),
                ("image_third", models.ImageField(upload_to="product/")),
            ],
        ),
        migrations.CreateModel(
            name="product_sizes_variants",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_quantity", models.PositiveIntegerField(default=0)),
                ("product_size", models.CharField(blank=True, max_length=10)),
                (
                    "product_data_id",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product_app.product_color_image",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=30)),
                ("product_description", models.TextField(blank=True)),
                ("product_image", models.ImageField(upload_to="product/")),
                ("product_price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "offer_percentage",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("product_added_at", models.DateField(auto_now=True)),
                ("product_updated_at", models.DateField(auto_now_add=True)),
                ("product_status", models.BooleanField(default=True)),
                ("product_delete", models.BooleanField(default=False)),
                (
                    "category_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="category_app.category",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product_color_image",
            name="product_id",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="product_app.products",
            ),
        ),
    ]
