# Generated by Django 5.0.4 on 2024-04-20 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product_color_image",
            name="image_fourth",
            field=models.ImageField(default="img coming", upload_to="product/"),
        ),
    ]
