# Generated by Django 5.0.4 on 2024-04-20 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_app", "0004_remove_products_product_delete_products_product_list"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="product_list",
            field=models.BooleanField(default=False),
        ),
    ]
