# Generated by Django 5.0.4 on 2024-04-21 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_app", "0005_alter_products_product_list"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="product_name",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
