# Generated by Django 5.0.4 on 2024-04-21 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_app", "0006_alter_products_product_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="product_color_image",
            name="product_variant_name",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
