# Generated by Django 5.0.4 on 2024-04-27 14:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_app", "0008_alter_product_sizes_variants_product_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product_sizes_variants",
            name="product_quantity",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MaxValueValidator(10000)]
            ),
        ),
    ]
