# Generated by Django 5.0.4 on 2024-04-27 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_app", "0009_alter_product_sizes_variants_product_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product_sizes_variants",
            name="product_data_id",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_size_qty",
                to="product_app.product_color_image",
            ),
        ),
    ]
