# Generated by Django 5.0.4 on 2024-04-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_app", "0011_product_color_image_list_product_color_image_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product_color_image",
            name="list",
        ),
        migrations.AddField(
            model_name="product_color_image",
            name="delete",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="product_color_image",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
