# Generated by Django 5.0.4 on 2024-04-27 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product_app", "0012_remove_product_color_image_list_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product_color_image",
            old_name="delete",
            new_name="delete_opt",
        ),
    ]
