# Generated by Django 5.0.4 on 2024-04-28 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_app", "0013_rename_delete_product_color_image_delete_opt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product_color_image",
            name="delete_opt",
            field=models.BooleanField(default=False),
        ),
    ]
