# Generated by Django 5.0.4 on 2024-05-02 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product_app", "0014_alter_product_color_image_delete_opt"),
    ]

    operations = [
        migrations.RenameField(
            model_name="products",
            old_name="product_status",
            new_name="product_delete",
        ),
    ]
