# Generated by Django 5.0.4 on 2024-05-02 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_app", "0015_rename_product_status_products_product_delete"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="product_delete",
            field=models.BooleanField(default=False),
        ),
    ]
