# Generated by Django 5.0.4 on 2024-05-17 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_app", "0017_alter_products_product_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product_color_image",
            name="status",
            field=models.BooleanField(default=True),
        ),
    ]
