# Generated by Django 5.0.4 on 2024-05-24 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_app", "0018_alter_product_color_image_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="product_color_image",
            name="featured",
            field=models.BooleanField(default=False),
        ),
    ]
