# Generated by Django 5.0.4 on 2024-06-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_app", "0019_product_color_image_featured"),
    ]

    operations = [
        migrations.AddField(
            model_name="product_color_image",
            name="review_data",
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name="product_color_image",
            name="review_star",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
