# Generated by Django 5.0.4 on 2024-04-29 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order_items",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="order_app.order",
            ),
        ),
    ]
