# Generated by Django 5.0.4 on 2024-05-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order_app", "0002_alter_order_items_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order_items",
            name="last_update",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="order_items",
            name="status",
            field=models.CharField(default="Out For Delivery", max_length=20),
        ),
    ]
