# Generated by Django 5.0.4 on 2024-05-05 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order_app", "0003_order_items_last_update_order_items_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="id",
        ),
        migrations.AlterField(
            model_name="order",
            name="serial_number",
            field=models.AutoField(
                editable=False, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
