# Generated by Django 5.0.4 on 2024-05-05 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order_app", "0004_remove_order_id_alter_order_serial_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="order_items",
            name="final_product_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
