# Generated by Django 5.0.4 on 2024-05-06 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order_app", "0005_order_items_final_product_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order_items",
            name="status",
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(default="Out For Delivery", max_length=20),
        ),
    ]
