# Generated by Django 5.0.4 on 2024-05-06 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order_app", "0006_remove_order_items_status_order_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="status",
        ),
        migrations.AddField(
            model_name="order_items",
            name="status",
            field=models.CharField(default="Out For Delivery", max_length=20),
        ),
    ]
