# Generated by Django 5.0.4 on 2024-05-06 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order_app", "0007_remove_order_status_order_items_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order_items",
            name="status",
            field=models.CharField(
                choices=[
                    ("Order Pending", "Order Pending"),
                    ("Order confirmed", "Order confirmed"),
                    ("Shipped", "Shipped"),
                    ("Out for delivery", "Out for delivery"),
                    ("Delivered", "Delivered"),
                    ("Cancelled", "Cancelled"),
                    ("Returned", "Returned"),
                ],
                default="Order Pending",
            ),
        ),
    ]
