# Generated by Django 5.0.4 on 2024-05-06 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order_app", "0008_alter_order_items_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order_items",
            name="cancel_return_confirm",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="order_items",
            name="status",
            field=models.CharField(
                choices=[
                    ("Order Pending", "Order Pending"),
                    ("Order confirmed", "Order confirmed"),
                    ("Shipped", "Shipped"),
                    ("Out For Delivery", "Out For Delivery"),
                    ("Delivered", "Delivered"),
                    ("Cancelled", "Cancelled"),
                    ("Returned", "Returned"),
                ],
                default="Order Pending",
            ),
        ),
        migrations.CreateModel(
            name="Cancelled_order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField(blank=True, null=True)),
                ("request_date", models.DateField(auto_now_add=True, null=True)),
                ("pickup_date", models.DateField(blank=True, null=True)),
                (
                    "has_dispatched",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "ordered_item",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="order_app.order_items",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
