# Generated by Django 5.0.4 on 2024-05-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order_app", "0010_order_items_accept_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="coupon_applied",
        ),
        migrations.AddField(
            model_name="order",
            name="coupon_discount",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="coupon_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
