# Generated by Django 5.0.4 on 2024-05-25 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "order_app",
            "0011_remove_order_coupon_applied_order_coupon_discount_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="order_items",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_all",
                to="order_app.order",
            ),
        ),
    ]
