# Generated by Django 5.0.4 on 2024-06-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order_app", "0012_alter_order_items_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="amount_to_pay",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
