# Generated by Django 5.0.4 on 2024-06-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order_app", "0013_order_amount_to_pay"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order_items",
            name="accept_order",
            field=models.BooleanField(default=True),
        ),
    ]
