# Generated by Django 5.0.4 on 2024-05-25 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("index_app", "0002_visitor_delete_monitor"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Visitor",
        ),
    ]
