# Generated by Django 5.0.4 on 2024-05-13 06:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupons_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupons",
            name="code",
            field=models.CharField(default="xxxx", max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name="coupons",
            name="created_on",
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name="coupons",
            name="discount_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="coupons",
            name="discount_percentage",
            field=models.PositiveIntegerField(
                default=0,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="coupons",
            name="expiry",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="coupons",
            name="is_active",
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name="coupons",
            name="max_limit",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="coupons",
            name="min_limit",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="coupons",
            name="title",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="coupons",
            name="valid_from",
            field=models.DateField(blank=True, null=True),
        ),
    ]
