# Generated by Django 5.0.4 on 2024-05-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupons_app", "0002_coupons_code_coupons_created_on_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupons",
            name="is_active",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
