# Generated by Django 5.0.4 on 2024-04-20 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="types_available",
        ),
        migrations.AddField(
            model_name="category",
            name="types_available",
            field=models.CharField(default="Other", max_length=20),
        ),
    ]
