# Generated by Django 5.0.4 on 2024-05-16 06:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category_app", "0002_remove_category_types_available_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="offer_percentage",
            field=models.PositiveIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
