# Generated by Django 5.0.4 on 2024-04-27 04:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.ImageField(upload_to="images/")),
            ],
        ),
        migrations.CreateModel(
            name="user_address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("landmark", models.CharField(blank=True, max_length=30, null=True)),
                ("address_type", models.CharField(default="Home", max_length=10)),
                ("accessible", models.CharField(default="Not Added", max_length=50)),
                ("area", models.CharField(default="Not Added", max_length=50)),
                ("city", models.CharField(default="Not Added", max_length=50)),
                (
                    "pincode",
                    models.CharField(
                        max_length=6,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Pincode must be 6 'digits'", regex="^\\d{6}$"
                            )
                        ],
                    ),
                ),
                ("post_office", models.CharField(default="Not Added", max_length=40)),
                ("state", models.CharField(default="Not Added", max_length=40)),
                (
                    "phone_no",
                    models.CharField(
                        default="00000000",
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be 10 'digits'",
                                regex="^\\d{10}$",
                            )
                        ],
                    ),
                ),
                (
                    "alternative_phone",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be 10 'digits'",
                                regex="^\\d{10}$",
                            )
                        ],
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
