# Generated by Django 5.0.4 on 2024-04-27 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_address",
            name="full_name",
            field=models.CharField(default="to add", max_length=50),
        ),
    ]
