# Generated by Django 5.0.4 on 2024-05-04 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_image_file_image_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_address",
            name="status_delete",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(upload_to="images/"),
        ),
    ]
