# Generated by Django 5.0.4 on 2024-04-28 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart_app", "0001_initial"),
        ("product_app", "0014_alter_product_color_image_delete_opt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="product_color_variant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="product_app.product_sizes_variants",
            ),
        ),
    ]
