# Generated by Django 5.0.4 on 2024-05-05 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart_app", "0004_remove_cart_product_color_variant_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
