# Generated by Django 5.0.4 on 2024-05-18 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart_app", "0008_cart_total_amount_without_coupon"),
        ("coupons_app", "0004_alter_coupons_discount_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="coupon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="coupons_app.coupons",
            ),
        ),
    ]
