# Generated by Django 5.0.4 on 2024-05-20 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart_app", "0009_alter_cart_coupon"),
        ("coupons_app", "0004_alter_coupons_discount_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="coupon_active",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="cart",
            name="coupon",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="coupons_app.coupons",
            ),
        ),
        migrations.AlterField(
            model_name="checkout",
            name="coupon",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="coupons_app.coupons",
            ),
        ),
    ]
